# -*- coding: utf-8 -*-
"""deeplearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6ZptGMPEMrPCAbzRFEFMl3atUZxa6tg
"""

from google import genai
client = genai.Client(api_key=" AIzaSyAJi-8oQUJl9I8rDDaoTcMa6lX20ebrT88")

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents='who is rohitsharma'
).text
print(response)